#!/bin/bash

echo "Enter first number:"
read a

echo "Enter second number:"
read b

echo "----------------------"
echo "MENU"
echo "1. Addition"
echo "2. Subtraction"
echo "3. Multiplication"
echo "4. Division"
echo "----------------------"

echo "Enter your choice:"
read choice

case $choice in

1)
    result=$((a + b))
    echo "Addition = $result"
    ;;

2)
    result=$((a - b))
    echo "Subtraction = $result"
    ;;

3)
    result=$((a * b))
    echo "Multiplication = $result"
    ;;

4)
    if [ $b -eq 0 ]; then
        echo "Division by zero not allowed"
    else
        result=$((a / b))
        echo "Division = $result"
    fi
    ;;

*)
    echo "Invalid choice"
    ;;
esac