#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Usage: $0 <string> <substring>"

    exit 1
fi

string=$1

substring=$2

count=0

temp=$string

while [[ "$temp" == *"$substring"* ]]
do
    temp="${temp#*"$substring"}"

    count=$((count + 1))
done

echo "Number of occurrences: $count"