#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 <number>"

    exit 1
fi

num=$1

factorial=1

if [ $num -lt 0 ]; then
    echo "Factorial not defined for negative numbers"

    exit 1
fi

for (( i=1; i<=num; i++ ))
do
    factorial=$((factorial * i))
done

echo "Factorial of $num is: $factorial"